// Mermaid Gantt text for a plan: one bar per topic, from its first learn session to its last review, plus the
// final practice day. Generated by our code, but topic titles originate from an LLM reading student material,
// so every label is reduced to a safe character set before it reaches Mermaid.

export type GanttItem = { date: string; kind: "learn" | "review" | "final"; topic: string };

const DATE = /^\d{4}-\d{2}-\d{2}$/;
const DAY = 86_400_000;
const days = (from: string, to: string) => Math.round((Date.parse(`${to}T00:00:00Z`) - Date.parse(`${from}T00:00:00Z`)) / DAY) + 1;

export const safeLabel = (s: string) =>
  s
    .replace(/[^\p{L}\p{M}\p{N} .,()/&+'-]/gu, " ")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 38) || "Session";

export function ganttSource(items: GanttItem[]): string {
  const spans = new Map<string, { start: string; end: string }>();
  let final: string | undefined;
  for (const i of items) {
    if (!DATE.test(i.date)) continue;
    if (i.kind === "final") {
      final = !final || i.date > final ? i.date : final;
      continue;
    }
    const key = i.topic.replace(/\s*\(part \d+\/\d+\)$/, ""); // both halves of a hard topic share one bar
    const s = spans.get(key);
    if (!s) spans.set(key, { start: i.date, end: i.date });
    else {
      if (i.date < s.start) s.start = i.date;
      if (i.date > s.end) s.end = i.date;
    }
  }
  const all = [...spans.values()]
    .flatMap((s) => [s.start, s.end])
    .concat(final ?? [])
    .sort();
  const span = all.length ? days(all[0], all[all.length - 1]) : 0;
  const lines = ["gantt", "  dateFormat YYYY-MM-DD", "  axisFormat %d %b", `  tickInterval ${span <= 21 ? "2day" : "1week"}`];
  let n = 0;
  if (spans.size) {
    lines.push("  section Topics");
    for (const [topic, s] of spans) lines.push(`  ${safeLabel(topic)} :t${++n}, ${s.start}, ${days(s.start, s.end)}d`);
  }
  if (final) lines.push("  section Final prep", `  Practice test :t${++n}, ${final}, 1d`);
  return lines.join("\n");
}
